[phases.setup]
cmds = [
    "cd backend/smart_parking_backend && pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "cd backend/smart_parking_backend && python manage.py collectstatic --noinput"
]

[start]
cmd = "cd backend/smart_parking_backend && python manage.py migrate && gunicorn smart_parking_backend.wsgi:application --bind 0.0.0.0:$PORT"

# Explicitly define providers
[providers]
python = "3.11"